/**
 * What the solve run tells the ticket, and what it tells whoever tunes triage.
 *
 * `orchestrator.ts` takes no Jira client on purpose — the caller owns labels and
 * comments. This is that caller's half: it turns a `SolveOutcome` into words,
 * and it is where the dev-lens correction finally goes somewhere.
 *
 * ## Why the dev lens is the point of this file
 *
 * Triage calls `agent:solvable` **without reading a line of source**: `--deep`
 * is hard-off and `Task` is not granted, so the fitness assessment is made from
 * the ticket text and the vault alone. Recon is the first thing in the pipeline
 * that opens the repository, so `devLensCorrection` is the only feedback that
 * assessment will ever receive. Until this module existed it was computed on
 * every run and dropped on the floor, which made the blind call permanently
 * blind — it could never be scored, so it could never improve.
 *
 * So the correction goes to two places, because it has two audiences:
 *
 *   - **the ticket**, for the person holding it, who needs to know an agent
 *     looked and what it concluded;
 *   - **`<OUTPUT_DIR>/dev-lens.md`**, append-only, for whoever is deciding
 *     whether the fitness call is trustworthy yet. That question is answered by
 *     reading fifty rows at once, not one ticket at a time, and a per-ticket
 *     comment cannot be counted.
 *
 * The local record is append-only and says so in its own header, unlike
 * `solve-cycle.md` beside it, which is a snapshot replaced every run. The
 * difference is deliberate: a snapshot answers "what is the queue doing now",
 * and calibration is a question about a trend.
 *
 * ## Posting is a capability the caller supplies, and today nobody supplies it
 *
 * `TicketCommenter` is one method wide. An implementation of it cannot
 * transition an issue, edit a field, or touch a label — the same reasoning as
 * `ClaimCapabilities`, and for the same reason: the type should tell a reviewer
 * the blast radius without them reading the implementation. Nothing in this
 * tree constructs one yet, so `reportOutcome` writes the local record and
 * reports that the comment was not posted. That is the honest state of the
 * phase, and it is visible in the return value rather than hidden in a log.
 *
 * ## The correction is untrusted text
 *
 * It is model-authored, but the model wrote it after reading a ticket anyone
 * with a Jira account can edit. Two defences, both in `safeText`, and both
 * about structure rather than taste — see there.
 */

import { mkdir, appendFile, readFile } from "node:fs/promises";
import { join } from "node:path";

import { logger } from "../logger.ts";
import { FOOTER_SENTINEL } from "../triage/gate.ts";
import type { SolveOutcome } from "./orchestrator.ts";

/** Append-only, and named so no issue key can collide with it. */
export const DEV_LENS_FILE = "dev-lens.md";

/**
 * Ends every comment this module posts, so a later run can find its own work.
 *
 * Distinct from triage's sentinel. Two bots writing to one ticket that shared a
 * marker would each treat the other's comment as its own to refresh, and the
 * loser's report would silently vanish at a moment unrelated to anything it did.
 */
export const SOLVE_SENTINEL = "_🤖 Generated by the solve pipeline._";

/** A way to say something on a ticket, and no way to do anything else. */
export interface TicketCommenter {
  comment: (issueKey: string, body: string) => Promise<void>;
}

export interface FeedbackDeps {
  readonly outputDirectory: string;
  /** Absent means the write path is not wired. The absence is the phase gate. */
  readonly commenter?: TicketCommenter;
}

/**
 * Makes untrusted text safe to place inside a structured document.
 *
 * Two defences, and neither is about politeness:
 *
 * 1. **Every whitespace run collapses to one space.** This document separates
 *    one section from the next with `##` headings and one row from the next
 *    with a newline. A correction containing a newline followed by `## ` would
 *    forge a section that the run never produced, in the one artifact a human
 *    reads to find out what the run concluded. Same defence, same reasoning, as
 *    `oneLine` in `report.ts`; markdown's remaining tricks can make a line ugly
 *    but cannot make it lie about structure. Pipes are escaped too, since the
 *    calibration record is a table and an unescaped pipe forges a column.
 *
 * 2. **Triage's footer sentinel is removed.** This is the sharper one. Triage
 *    identifies its own comment — the one it overwrites in place on every
 *    re-run — by author *and* that exact sentinel. Both bots post under the
 *    same Jira account, so a correction carrying the sentinel through to a
 *    posted comment would make the next triage run adopt *our* comment as its
 *    own and overwrite the solve report with a triage report. Cheap to prevent
 *    here, and impossible to notice afterwards.
 */
export function safeText(text: string): string {
  return text
    .replaceAll(FOOTER_SENTINEL, "[sentinel removed]")
    .replaceAll(/\s+/gu, " ")
    .replaceAll("|", "\\|")
    .trim();
}

/**
 * The dev-lens feedback an outcome carries, if it got far enough to have any.
 *
 * `?? null` covers a case the types say cannot happen: an outcome whose kind is
 * not `no-worktree` but which carries no `devLens`. Handled rather than
 * asserted, on the same grounds `report.ts` gives for `ticketLines` — this
 * module runs at the end of every solve, including the ones that went badly,
 * and a diagnostic that throws while explaining a problem replaces a real
 * finding with a stack trace about itself.
 */
function lensOf(outcome: SolveOutcome): { accurate: boolean; correction: string } | null {
  // `crashed` joins `no-worktree` here for a different reason worth keeping
  // straight: not that no pass ran, but that the pass which produces the lens
  // may be the one that died. An absent correction is honest; a fabricated one
  // would feed the fitness assessment evidence nobody gathered.
  //
  // Deleting the `crashed` clause kills no test, and the honest reason is that
  // it cannot: `crashed` carries no `devLens` field, so `?? null` reaches the
  // same answer by accident. What does catch it is `tsc` — the property does
  // not exist on that member of the union, so the narrowing is load-bearing at
  // compile time even though it is inert at run time. Recorded as mechanically
  // enforced by the type checker rather than by a test, in the same spirit as
  // the backstop notes in `worktree.ts` and `verify.ts`.
  //
  // `unusable-base` joins them for the first reason rather than the second: it
  // is decided before recon runs, so there is no lens to be accurate or
  // inaccurate about. Scoring the fitness call on a run that never read the
  // code would credit or blame triage for a broken build.
  return outcome.kind === "no-worktree" ||
    outcome.kind === "crashed" ||
    outcome.kind === "unusable-base"
    ? null
    : (outcome.devLens ?? null);
}

/**
 * One sentence saying what happened, in terms of who has to act.
 *
 * The three shapes of "no" that `orchestrator.ts` works to keep apart are worth
 * nothing if they arrive on the ticket as one word. `refused` in particular
 * must not read like `failed`: it says the harness declined to judge, which is
 * a statement about the harness, and a reader who takes it as a statement about
 * their code will go looking for a bug that was never reported.
 */
function headline(outcome: SolveOutcome): string {
  switch (outcome.kind) {
    case "no-worktree": {
      return `No branch could be cut, so nothing was attempted: ${safeText(outcome.reason)}`;
    }
    case "unusable-base": {
      // Phrased to put the repository, not the ticket, in the reader's way. The
      // ticket may be perfectly solvable; this run could not have told anyone.
      //
      // This frames the reason rather than summarising it, and the summary it
      // replaces was wrong in two directions at once. `verifyBase` already
      // returns a complete sentence, carefully qualified — *in a fresh
      // worktree*, and *a fact about the repository or this harness* — so
      // restating it here printed the claim twice and the first copy had both
      // qualifiers stripped, telling a Jira reader that `main` is broken. On
      // the other branch it was not merely unqualified but false: when the
      // build could not be *run*, a headline asserting it "does not pass"
      // states as fact the one thing that run failed to establish.
      //
      // So the rule for this case is deliberately narrow — say who has to act
      // and defer on what happened, because the layer that found out has
      // already said it better and knows which of the two things went wrong.
      return `Nothing was attempted and nothing can be concluded about this ticket, because ${safeText(
        outcome.reason,
      )}`;
    }
    case "bailed": {
      return `An agent read the code and stopped before changing anything: ${safeText(
        outcome.reason,
      )}`;
    }
    case "abandoned": {
      // The two causes are opposite claims and must not share a sentence. A
      // `judgement` abandon says the ticket was misjudged; an `environment`
      // abandon says this machine got in the way and the ticket was never
      // reached. Phrased in the same register as `crashed` for that reason —
      // it is the same class of statement.
      return outcome.cause === "environment"
        ? `An agent was prevented from working — this is about the machine, not the ticket, and says nothing about whether it is solvable: ${safeText(
            outcome.reason,
          )}`
        : `An agent read the code and judged the change should not be made as briefed: ${safeText(
            outcome.reason,
          )}`;
    }
    case "refused": {
      return `An agent made a change, but the harness would not judge it (${outcome.stage}), so nothing here says whether the change was any good: ${outcome.reasons
        .map((reason) => safeText(reason))
        .join("; ")}`;
    }
    case "failed": {
      return `An agent made a change and this repository's own checks rejected it: ${safeText(
        outcome.reason,
      )}`;
    }
    case "crashed": {
      // Phrased to be unmistakably about the harness. This is the outcome most
      // likely to be misread as "the agent could not do it", which would put a
      // false data point into the fitness assessment.
      return `The ${outcome.pass} step did not finish, so nothing was judged and this says nothing about whether the ticket is solvable: ${safeText(
        outcome.reason,
      )}`;
    }
    case "verified": {
      return `An agent changed ${outcome.files} file(s), ${outcome.lines} line(s), and the repository's own checks passed.`;
    }
  }
}

/**
 * Whether a human should be told the fitness call was wrong.
 *
 * An accurate lens is not worth a paragraph on the ticket — it is worth a row
 * in the calibration record, which is where accurate readings are counted.
 */
function correctionBlock(outcome: SolveOutcome): readonly string[] {
  const lens = lensOf(outcome);
  if (lens === null || lens.accurate) {
    return [];
  }
  return [
    "",
    "**The triage assessment was off.** The `agent:solvable` call is made without",
    "reading any source, so this is the first look at the actual code:",
    "",
    `> ${safeText(lens.correction) || "no correction was given"}`,
  ];
}

/** The ticket comment. Pure, so it is testable without a Jira account. */
export function renderSolveComment(issueKey: string, outcome: SolveOutcome): string {
  return [
    `## Solve attempt — ${issueKey}`,
    "",
    headline(outcome),
    ...correctionBlock(outcome),
    "",
    "A human merges. This bot has no merge path.",
    "",
    SOLVE_SENTINEL,
  ].join("\n");
}

/**
 * Written once, when the record does not exist yet.
 *
 * The annotation paragraph is in here rather than only in the file because the
 * file is gitignored: a convention documented solely in the artifact is lost the
 * first time the artifact is regenerated, and what comes back is a record whose
 * rows carry hand-written notes its own header does not admit to allowing.
 */
const HEADER = [
  "# Dev-lens calibration",
  "",
  "One row per solve attempt, appended, never rewritten. Triage calls `agent:solvable`",
  "from the ticket text alone — it cannot read source — and recon is the first pass that",
  "can. This is the scoreboard for that blind call: read the `Lens` column down the page",
  "before trusting it enough to turn autosolve on.",
  "",
  '**One exception to "never rewritten", and it is narrow on purpose.** A row\'s `Correction`',
  "cell may be annotated by hand when the run's outcome is accurate but misleading without",
  "context a later run supplied. The recorded verdict is never edited — a run that failed",
  "stays `failed`, because that is what happened — and the annotation says who is at fault",
  "instead. Anything wider than that turns a scoreboard into an argument. Annotations are",
  "marked `[annotated <date>]`.",
  "",
  "| When | Ticket | Outcome | Lens | Correction |",
  "| --- | --- | --- | --- | --- |",
  "",
].join("\n");

/**
 * The `Outcome` column, which is read down the page as a scoreboard.
 *
 * `abandoned` alone is the one kind that means two incompatible things, and the
 * table is the place where that matters most: a reader counting abandons to
 * decide whether triage's blind call can be trusted would be counting the
 * host's safety hook among the ticket's own failures. The cause is appended
 * rather than folded into a second column so old rows stay readable.
 */
function outcomeLabel(outcome: SolveOutcome): string {
  return outcome.kind === "abandoned" ? `abandoned (${outcome.cause})` : outcome.kind;
}

/** One table row. Pure. */
export function calibrationRow(issueKey: string, outcome: SolveOutcome, now: Date): string {
  const lens = lensOf(outcome);
  const verdict = lens === null ? "n/a" : lens.accurate ? "ok" : "**wrong**";
  const correction = lens === null || lens.accurate ? "—" : safeText(lens.correction) || "—";
  return `| ${now.toISOString()} | ${issueKey} | ${outcomeLabel(outcome)} | ${verdict} | ${correction} |\n`;
}

/**
 * Appends one row, writing the header first if this is the first run.
 *
 * The header is written only when the file does not already start with it,
 * rather than only when the file is absent. An empty file left behind by an
 * interrupted first write would otherwise collect rows under no table at all,
 * and a markdown table without its header row does not render as a table.
 */
export async function recordDevLens(
  directory: string,
  issueKey: string,
  outcome: SolveOutcome,
  now: Date,
): Promise<string> {
  await mkdir(directory, { recursive: true });
  const path = join(directory, DEV_LENS_FILE);
  const existing = await readFile(path, "utf8").catch(() => "");
  await appendFile(
    path,
    (existing.startsWith("# Dev-lens") ? "" : HEADER) + calibrationRow(issueKey, outcome, now),
    "utf8",
  );
  return path;
}

export interface FeedbackResult {
  /** Where the calibration row landed. */
  readonly recordPath: string;
  /** The comment body, whether or not anything posted it. */
  readonly comment: string;
  readonly posted: boolean;
  /** Why not, when `posted` is false. */
  readonly reason?: string;
}

/**
 * Records the outcome locally and, if a commenter was supplied, on the ticket.
 *
 * The local record is written **first and unconditionally**. It is the cheaper
 * and more durable of the two, and a run that manages to comment on Jira but
 * loses its own calibration row has thrown away the only part of this that
 * accumulates.
 *
 * A failed comment does not throw. By the time this is called the work is done
 * and, in the `verified` case, already pushed; turning "we could not annotate
 * the ticket" into an exception would let a reporting problem look like a solve
 * problem, which is the exact confusion the outcome types spend so much effort
 * keeping apart.
 */
export async function reportOutcome(
  deps: FeedbackDeps,
  issueKey: string,
  outcome: SolveOutcome,
  now: Date,
): Promise<FeedbackResult> {
  const recordPath = await recordDevLens(deps.outputDirectory, issueKey, outcome, now);
  const comment = renderSolveComment(issueKey, outcome);
  const lens = lensOf(outcome);

  logger.info("solve.feedback", {
    issueKey,
    outcome: outcomeLabel(outcome),
    devLensAccurate: lens?.accurate ?? null,
  });

  if (deps.commenter === undefined) {
    return {
      recordPath,
      comment,
      posted: false,
      reason: "no commenter is wired, so nothing was posted to Jira",
    };
  }

  try {
    await deps.commenter.comment(issueKey, comment);
    return { recordPath, comment, posted: true };
  } catch (error) {
    const reason = error instanceof Error ? error.message : String(error);
    logger.warn("solve.feedback.not_posted", { issueKey, reason });
    return { recordPath, comment, posted: false, reason };
  }
}
