/**
 * What the solve run tells the ticket, and what it tells whoever tunes triage.
 *
 * `orchestrator.ts` takes no Jira client on purpose — the caller owns labels and comments. This
 * turns a `SolveOutcome` into words, posts the dev-lens correction, and appends a calibration row
 * to `dev-lens.md` (append-only, unlike the snapshot `solve-cycle.md` beside it) so the blind
 * `agent:solvable` call in triage can eventually be scored.
 *
 * `reportOutcome` is also where the repair round's row is appended, to its own page — see
 * `repair-ledger.ts` for why that is a sibling and not a seventh column here.
 *
 * `TicketCommenter` is one method wide, the same reasoning as `ClaimCapabilities`: the type tells
 * a reviewer the blast radius without them reading the implementation. An absent `commenter` means
 * only one thing — the run succeeded and opened a pull request instead; see `reportsToTicket`.
 *
 * The correction is model-authored text read from a ticket anyone with a Jira account can edit;
 * `ledger.ts`'s `safeText` defends against it being read as structure.
 */

import { createLogger } from "../logger.ts";
import { shorten } from "../text.ts";
import { appendLedgerRow, safeText } from "./ledger.ts";
import type { SolveOutcome } from "./orchestrator.ts";
import { recordRepairRound } from "./repair-ledger.ts";

const log = createLogger("solve");

/** Append-only, and named so no issue key can collide with it. */
export const DEV_LENS_FILE = "dev-lens.md";

/**
 * Ends every comment this module posts, so a later run can find its own work.
 *
 * Distinct from triage's sentinel. Two bots writing to one ticket that shared a
 * marker would each treat the other's comment as its own to refresh, and the
 * loser's report would silently vanish at a moment unrelated to anything it did.
 */
export const SOLVE_SENTINEL = "_🤖 Generated by the solve pipeline._";

/** A way to say something on a ticket, and no way to do anything else. */
export interface TicketCommenter {
  comment: (issueKey: string, body: string) => Promise<void>;
}

export interface FeedbackDeps {
  readonly outputDirectory: string;
  /**
   * Absent means *do not post*; `reportsToTicket` supplies one for every outcome but `verified`.
   * Kept optional because a caller that wants the calibration row without a Jira write is legitimate.
   */
  readonly commenter?: TicketCommenter;
}

/**
 * How much of each part of a bail reaches the ticket. A schema description asking for one or two
 * sentences per blocker is a request, not a guarantee — these are the enforced caps.
 */
const LIMITS = {
  /** The first line of the comment, read on its own in a notification. */
  headline: 300,
  /** One bullet, scanned against five others. */
  blocker: 300,
  /** Six is already a longer list than anyone acts on in one sitting. */
  blockers: 6,
  /** The actionable half, so it gets the most room of the three. */
  remedy: 800,
} as const;

/**
 * The dev-lens feedback an outcome carries, if it got far enough to have any.
 * `?? null` covers a case the types disallow — handled rather than asserted, since a diagnostic
 * that throws while explaining a problem replaces a real finding with a stack trace about itself.
 */
function lensOf(outcome: SolveOutcome): { accurate: boolean; correction: string } | null {
  // `crashed`: the pass that produces the lens may be itself the one that died, so a fabricated
  // correction would feed the fitness assessment evidence nobody gathered. `unusable-base`: decided
  // before recon runs, so there is no lens. `escaped`: overrides the run's verdict, so scoring it
  // would credit or blame triage for a verdict this outcome just withdrew.
  return outcome.kind === "no-worktree" ||
    outcome.kind === "crashed" ||
    outcome.kind === "unusable-base" ||
    outcome.kind === "escaped"
    ? null
    : (outcome.devLens ?? null);
}

/**
 * One sentence saying what happened, in terms of who has to act.
 * `refused` must not read like `failed`: it says the harness declined to judge, not that the code is wrong.
 */
function headline(outcome: SolveOutcome): string {
  switch (outcome.kind) {
    case "no-worktree": {
      return `No branch could be cut, so nothing was attempted: ${safeText(outcome.reason)}`;
    }
    case "unusable-base": {
      // Says who has to act and defers on what happened: `verifyBase`'s reason is already
      // qualified ("in a fresh worktree", "a fact about the repository or this harness"), and
      // restating it here risks dropping a qualifier and asserting more than the run established.
      return `Nothing was attempted and nothing can be concluded about this ticket, because ${safeText(
        outcome.reason,
      )}`;
    }
    case "bailed": {
      // Capped as well as sectioned: `bailReason` is one sentence here, and detail lives below.
      return `An agent read the code and stopped before changing anything: ${shorten(
        safeText(outcome.reason),
        LIMITS.headline,
      )}`;
    }
    case "abandoned": {
      // The two causes are opposite claims and must not share a sentence: `environment` says the
      // machine got in the way; `judgement` says the ticket was misjudged as briefed.
      return outcome.cause === "environment"
        ? `An agent was prevented from working — this is about the machine, not the ticket, and says nothing about whether it is solvable: ${safeText(
            outcome.reason,
          )}`
        : `An agent read the code and judged the change should not be made as briefed: ${safeText(
            outcome.reason,
          )}`;
    }
    case "refused": {
      return `An agent made a change, but the harness would not judge it (${outcome.stage}), so nothing here says whether the change was any good: ${outcome.reasons
        .map((reason) => safeText(reason))
        .join("; ")}`;
    }
    case "escaped": {
      // Withholds the run and names the alternate explanation — the guard cannot distinguish a
      // stray write from the operator editing one of these checkouts while the solve ran.
      return `Files changed outside this run's own working copy while it was in flight, so nothing it produced is being offered${
        outcome.would === "verified"
          ? " — including a change that had otherwise passed every check"
          : ""
      }. Checkouts affected: ${outcome.paths
        .map((path) => safeText(path))
        .join(
          ", ",
        )}. If you were editing those yourself while this ran, that is the likely cause and the run can simply be repeated.`;
    }
    case "failed": {
      const rejected = `An agent made a change and this repository's own checks rejected it: ${safeText(
        outcome.reason,
      )}`;
      // Written before verification ran, so it is the pass's prediction rather than a diagnosis — and it is frequently the failure itself, named by the only party who read the change.
      const risk = outcome.fix.residualRisk.trim();
      const flagged =
        risk === ""
          ? rejected
          : `${rejected}\n\nThe agent flagged this about its own change, before the checks ran: ${safeText(risk)}`;
      if (outcome.repairOutcome === undefined) {
        return flagged;
      }
      // On the ticket, not only the terminal: under the daemon nobody is watching one, and a round
      // reported nowhere is indistinguishable from a round that never ran.
      const attempt =
        outcome.repairOutcome === "verified"
          ? `A second agent was then shown the failure and its corrected version passed the same checks — but that result is **not** being acted on and no pull request is being opened. Acting on a repaired result is a separate decision, made per run, because making a failing check pass by weakening it looks identical from here.`
          : `A second agent was then shown the failure and did not resolve it either (${safeText(outcome.repairOutcome)}).`;
      const repairRisk = outcome.repair?.residualRisk.trim() ?? "";
      return repairRisk === ""
        ? `${flagged}\n\n${attempt}`
        : `${flagged}\n\n${attempt}\n\nThat second agent flagged this about its own edit: ${safeText(repairRisk)}`;
    }
    case "crashed": {
      // Phrased to be unmistakably about the harness — misread as "the agent could not do it", it
      // would put a false data point into the fitness assessment.
      return `The ${outcome.pass} step did not finish, so nothing was judged and this says nothing about whether the ticket is solvable: ${safeText(
        outcome.reason,
      )}`;
    }
    case "verified": {
      return `An agent changed ${outcome.files} file(s), ${outcome.lines} line(s), and the repository's own checks passed.`;
    }
  }
}

/**
 * Whether a human should be told the fitness call was wrong.
 * An accurate lens belongs in the calibration record, not a paragraph on the ticket.
 */
function correctionBlock(outcome: SolveOutcome): readonly string[] {
  const lens = lensOf(outcome);
  if (lens === null || lens.accurate) {
    return [];
  }
  return [
    "",
    "**The triage assessment was off.** The `agent:solvable` call is made without",
    "reading any source, so this is the first look at the actual code:",
    "",
    `> ${safeText(lens.correction) || "no correction was given"}`,
  ];
}

/**
 * The two sections a bail owes the person holding the ticket: what blocks it and what would fix
 * it, from separate schema fields rather than one string that `safeText` would flatten into a
 * wall of text.
 * §5 of the plan records the pattern this closes: the remedy is the only actionable part, so it
 * gets the most room and the last word before the footer. Absent fields render nothing rather
 * than an empty heading.
 */
function bailDetail(outcome: SolveOutcome): readonly string[] {
  // No other member of the union carries these fields; `tsc` enforces this at compile time even
  // though it's inert at run time — same standing as the `crashed` clause in `lensOf`.
  if (outcome.kind !== "bailed") {
    return [];
  }
  // Defensively read, like `lensOf`: a renderer that throws here would discard the headline that
  // was already composed, not just this section.
  const recon = outcome.recon as Partial<typeof outcome.recon> | undefined;
  const blockers = (recon?.bailBlockers ?? [])
    .map((blocker) => safeText(blocker))
    .filter((blocker) => blocker !== "");
  const remedy = safeText(recon?.bailRemedy ?? "");
  const extra = blockers.length - LIMITS.blockers;

  return [
    ...(blockers.length === 0
      ? []
      : [
          "",
          "**What is in the way**",
          "",
          ...blockers
            .slice(0, LIMITS.blockers)
            .map((blocker) => `* ${shorten(blocker, LIMITS.blocker)}`),
          // Said rather than dropped silently — an unmarked truncation would let a reporter split the ticket against an incomplete blocker list.
          ...(extra > 0 ? [`* …and ${String(extra)} more, in the run's own report.`] : []),
        ]),
    ...(remedy === ""
      ? []
      : ["", "**To make this agent-solvable**", "", shorten(remedy, LIMITS.remedy)]),
  ];
}

/**
 * The ticket comment. Pure, so it is testable without a Jira account.
 * Never renders for `verified` — the only outcome with a pull request — because `reportsToTicket`
 * withholds the commenter for it.
 */
export function renderSolveComment(issueKey: string, outcome: SolveOutcome): string {
  return [
    `## Solve attempt — ${issueKey}`,
    "",
    headline(outcome),
    ...bailDetail(outcome),
    ...correctionBlock(outcome),
    "",
    SOLVE_SENTINEL,
  ].join("\n");
}

/**
 * Written once, when the record does not exist yet.
 * Duplicated here rather than living only in the file: the file is gitignored, so a convention
 * documented solely in the artifact is lost the first time the artifact regenerates.
 */
const HEADER = [
  "# Dev-lens calibration",
  "",
  "One row per solve attempt, appended, never rewritten. Triage calls `agent:solvable`",
  "from the ticket text alone — it cannot read source — and recon is the first pass that",
  "can. This is the scoreboard for that blind call: read the `Lens` column down the page",
  "before trusting it enough to turn autosolve on.",
  "",
  '**One exception to "never rewritten", and it is narrow on purpose.** A row\'s `Correction`',
  "cell may be annotated by hand when the run's outcome is accurate but misleading without",
  "context a later run supplied. The recorded verdict is never edited — a run that failed",
  "stays `failed`, because that is what happened — and the annotation says who is at fault",
  "instead. Anything wider than that turns a scoreboard into an argument. Annotations are",
  "marked `[annotated <date>]`.",
  "",
  "| When | Ticket | Outcome | Lens | Correction |",
  "| --- | --- | --- | --- | --- |",
  "",
].join("\n");

/**
 * The `Outcome` column, read down the page as a scoreboard.
 * `abandoned` is the one kind meaning two incompatible things; the cause is appended rather than
 * folded into a second column so old rows stay readable.
 */
function outcomeLabel(outcome: SolveOutcome): string {
  return outcome.kind === "abandoned" ? `abandoned (${outcome.cause})` : outcome.kind;
}

/** One table row. Pure. */
export function calibrationRow(issueKey: string, outcome: SolveOutcome, now: Date): string {
  const lens = lensOf(outcome);
  const verdict = lens === null ? "n/a" : lens.accurate ? "ok" : "**wrong**";
  const correction = lens === null || lens.accurate ? "—" : safeText(lens.correction) || "—";
  return `| ${now.toISOString()} | ${issueKey} | ${outcomeLabel(outcome)} | ${verdict} | ${correction} |\n`;
}

/** Appends one row, writing the header first if this is the first run. */
export async function recordDevLens(
  directory: string,
  issueKey: string,
  outcome: SolveOutcome,
  now: Date,
): Promise<string> {
  return await appendLedgerRow(
    directory,
    DEV_LENS_FILE,
    HEADER,
    calibrationRow(issueKey, outcome, now),
  );
}

export interface FeedbackResult {
  /** Where the calibration row landed. */
  readonly recordPath: string;
  /**
   * Where the repair-round row landed. Absent rather than empty when no round ran, so a caller
   * cannot print a path for one that never happened.
   */
  readonly repairRecordPath?: string;
  /** The comment body, whether or not anything posted it. */
  readonly comment: string;
  readonly posted: boolean;
  /** Why not, when `posted` is false. */
  readonly reason?: string;
}

/**
 * Records the outcome locally and, if a commenter was supplied, on the ticket.
 *
 * Local records are written first and unconditionally, being the more durable of the two. A failed
 * comment does not throw: the work is already done, and turning "could not annotate the ticket"
 * into an exception would make a reporting problem look like a solve problem. Both scoreboards are
 * written here because the daemon and `solve:once` share this function and nothing else.
 */
export async function reportOutcome(
  deps: FeedbackDeps,
  issueKey: string,
  outcome: SolveOutcome,
  now: Date,
): Promise<FeedbackResult> {
  const recordPath = await recordDevLens(deps.outputDirectory, issueKey, outcome, now);
  const repairRecordPath = await recordRepairRound(deps.outputDirectory, issueKey, outcome, now);
  const comment = renderSolveComment(issueKey, outcome);
  const lens = lensOf(outcome);

  const written = {
    recordPath,
    ...(repairRecordPath === null ? {} : { repairRecordPath }),
    comment,
  };

  log.info("solve.feedback", {
    issueKey,
    outcome: outcomeLabel(outcome),
    devLensAccurate: lens?.accurate ?? null,
    // Also in `solve.repair.dry_run`, written by the pipeline rather than the reporter: a round
    // recorded nowhere shows up as the two disagreeing.
    repairRound: repairRecordPath !== null,
  });

  if (deps.commenter === undefined) {
    return {
      ...written,
      posted: false,
      reason: "no commenter is wired, so nothing was posted to Jira",
    };
  }

  try {
    await deps.commenter.comment(issueKey, comment);
    return { ...written, posted: true };
  } catch (error) {
    const reason = error instanceof Error ? error.message : String(error);
    log.warn("solve.feedback.not_posted", { issueKey, reason });
    return { ...written, posted: false, reason };
  }
}
