/**
 * The check that stands between deciding and posting.
 *
 * This is the piece that was missing. The skill used to post its comment
 * mid-run, so by the time `structured_output` arrived — the only thing this
 * service can inspect — the comment was already on the ticket. Every check we
 * could write was therefore a post-mortem. On SSX-3822 that meant reading a
 * `dor:pass` off the board that the run's own scorecard contradicted, and being
 * able to do nothing about it but re-run.
 *
 * Now the analyst returns the mutation instead of performing it, and this
 * function is what decides whether the poster is dispatched at all. Refusing
 * here means nothing was sent, which is the difference between a guard and a
 * report.
 *
 * Two properties worth stating, because they shaped the code:
 *
 * 1. Every violation is collected, not just the first. An operator reading a
 *    refusal wants the list, and a run costs real money — sending them back
 *    round the loop once per problem would be miserly with the wrong resource.
 *
 * 2. The checks are mechanical. Nothing here asks a model whether the verdict
 *    is good; each rule is one that `INTAKE_INSTRUCTIONS.md` states as an
 *    absolute, and so can be enforced by string comparison. This gate cannot
 *    tell you a verdict is *wrong* — only that it contradicts itself or breaks
 *    a rule the skill set for itself.
 */

import { AGENT_LABELS } from "../solve/labels.ts";
import { type Mutation, TriageError, type TriagePayload, assertDorCoherent } from "./runner.ts";

/**
 * The §11 idempotency sentinel, verbatim.
 *
 * Load-bearing rather than decorative: the skill recognises its own prior
 * comment by this exact line plus its own authorship. A body that omits it can
 * still be posted, but it can never be *updated* — so every re-run would stack
 * another copy on the ticket instead of refreshing the last one. Checking for
 * it costs one `endsWith` and prevents a slow mess.
 */
export const FOOTER_SENTINEL = "_🤖 Generated by intake-triage · re-run the command to refresh._";

/** The only components §11 permits the skill to set. Cap of one. */
export const POLICY_STREAMS: ReadonlySet<string> = new Set([
  "SSX Advisor",
  "EDH",
  "SSX Partner",
  "SSX Nettsalg",
]);

/**
 * Label namespaces the skill owns, and may therefore remove.
 *
 * §11: "remove ONLY the skill's own stale namespaced labels (`route:*`,
 * `dup:*`, `dor:*`, `tier:*`, `intake:*`, `next:*`); never touch a human
 * label." A human label reaching `labelsRemove` is the one mistake in this
 * payload that destroys information belonging to someone else, so it is checked
 * rather than trusted.
 *
 * This list must match that sentence exactly — not a superset. A gate looser
 * than the contract it enforces has a hole in it; an earlier version also
 * listed `comp:`, which no part of the skill actually sets.
 *
 * `next:` was the interesting case. It was missing from §11 while being set by
 * the skill on every verdict, so enforcing the five literally refused the whole
 * mutation on any verdict change — including the correction to SSX-3822, which
 * had to clear a stale `next:to-trio` to stop it contradicting the
 * `next:to-reporter` replacing it. The fix was to §11, not to this list: the
 * enumeration was an incomplete rendering of the real rule, which is "never
 * touch a human label". Widen this only by widening §11 first.
 */
const OWNED_LABEL_NAMESPACES: readonly string[] = [
  "route:",
  "dup:",
  "dor:",
  "tier:",
  "intake:",
  "next:",
  "agent:",
];

/**
 * Namespaces the skill also writes, removable only as half of a swap.
 *
 * The asymmetry these fix: §11's removal list named the *assessments* and not the
 * *taxonomy*, while the skill's label vocabulary sets both. So a re-triage could
 * revise its verdict freely and could never revise a fact — a ticket re-routed to
 * another squad kept the old `team:` beside the new one, and a corrected `svc:`
 * left two, which `repoFromLabels` reads as ambiguous and resolves to `null`. The
 * skill was the only writer of those labels and the only party unable to fix them.
 *
 * They are not simply moved into the list above, because the two kinds fail
 * differently. A missing `dor:` label is a verdict not yet reached. A missing
 * `svc:` is a fact deleted — and the value it decides is which repository a solver
 * may write to. So removal here is permitted only when the same mutation adds at
 * least one label in the same namespace: a replacement, never a bare deletion. A
 * model that gets the new value wrong is a wrong label, which the next re-triage
 * corrects; a model that removes and adds nothing is a hole no re-triage notices,
 * because the ticket then looks like one that was never triaged.
 *
 * "At least one", not "exactly one", because `team:` is legitimately multi-valued
 * on dual-owned repos, and a rule that forced a 1:1 swap would block the honest
 * case of one owner becoming two.
 *
 * `impl-uncertain` is deliberately absent and stays unremovable: it is a bare
 * label rather than a namespaced one (`labels.ts`), so it has no namespace to
 * swap within, and the rule above has nothing to bite on. Widening for it would
 * mean naming a single literal, which is a different decision from this one.
 */
const REVISABLE_LABEL_NAMESPACES: readonly string[] = [
  "team:",
  "jira:",
  "domain:",
  "svc:",
  "value:",
  "effort:",
];

/**
 * The only `agent:` label triage may touch — and the reason the namespace above
 * is not enough on its own.
 *
 * `agent:` is the first namespace this service shares with something other than
 * the skill. Triage contributes an assessment, `agent:solvable`. A human
 * contributes `agent:start`, which is the authorisation for a bot to attempt a
 * fix. A solver contributes `agent:solving` / `agent:done` / `agent:failed`,
 * which are its own lifecycle.
 *
 * Only the first of those is triage's to write, and the gap matters more than it
 * looks. The analyst's entire input is a Jira ticket, and a Jira ticket is
 * written by whoever felt like writing one — it is data, not instruction. If the
 * skill could emit `agent:start`, then a ticket body could ask it to, and the
 * human authorisation step in manual mode would be one that the thing being
 * authorised is able to perform for itself. Enforcing the narrower rule costs a
 * set lookup, so there is no reason to rely on the model declining.
 *
 * The same argument applies to removal: a re-triage that cleared `agent:solving`
 * would unclaim a solve already in flight, and the queue's idempotency rests on
 * that label being written exactly once by exactly one writer.
 *
 * **`agent:watching` joined it for F, and it is the first widening of this set.**
 * It belongs on the same side of the line as `agent:solvable` by the test the
 * paragraphs above imply: both are triage's own assessment of a ticket, neither
 * authorises anything to touch code, and both must be *removable* by a later
 * triage of the same ticket — a watch that outlived the gap it was watching for
 * is the thing F exists to end. What it does authorise is spend, which is why it
 * is bounded elsewhere rather than left to the model's restraint.
 *
 * Note what stayed out, because the ticket-as-data argument is unchanged and the
 * new label does not weaken it: a ticket body can now talk this skill into
 * putting itself on a watch list, which costs re-triage runs, and it still
 * cannot talk it into `agent:start`, which costs a pull request.
 */
const TRIAGE_OWNED_AGENT_LABELS: ReadonlySet<string> = new Set([
  AGENT_LABELS.solvable,
  AGENT_LABELS.watching,
]);

/** The mutation may not be posted. Carries every reason, not the first. */
export class UnpostableError extends TriageError {
  readonly issueKey: string;
  readonly violations: readonly string[];

  constructor(issueKey: string, violations: readonly string[]) {
    super(
      `${issueKey}: refusing to post — ${String(violations.length)} problem(s) with the mutation:\n` +
        violations.map((violation) => `  - ${violation}`).join("\n"),
    );
    this.name = "UnpostableError";
    this.issueKey = issueKey;
    this.violations = violations;
  }
}

/**
 * Throws unless every mechanical rule holds.
 *
 * Re-runs `assertDorCoherent` even though `parsePayload` already did. That is
 * not redundancy for its own sake: this function is the documented last thing
 * that happens before a write, and a caller reading it should be able to see
 * the full set of conditions without tracing back through the parser. It also
 * means a future caller that builds a payload some other way still gets the
 * coherence check.
 */
export function assertPostable(payload: TriagePayload, issueKey: string): void {
  assertDorCoherent(payload, issueKey);

  const violations = [
    ...checkComment(payload, issueKey),
    ...checkLabels(payload),
    ...checkComponent(payload.mutation),
    ...checkAgentFitness(payload),
  ];

  if (violations.length > 0) {
    throw new UnpostableError(issueKey, violations);
  }
}

function checkComment(payload: TriagePayload, issueKey: string): readonly string[] {
  const body = payload.mutation.commentBody;
  const violations: string[] = [];

  if (body.trim() === "") {
    // Nothing else about the comment is worth reporting once this is true, and
    // the follow-on complaints would bury the one that matters.
    return ["the comment body is empty, so there is nothing to post"];
  }

  if (!body.trimEnd().endsWith(FOOTER_SENTINEL)) {
    violations.push(
      `the comment body does not end with the §11 footer sentinel, so a re-run could not update it in place and would post a second copy instead`,
    );
  }

  if (!body.includes(issueKey)) {
    // Cheap guard against the wrong ticket's comment being posted — the poster
    // is given a body it did not write, so this is the one place the pairing of
    // body to key is ever checked.
    violations.push(
      `the comment body never mentions ${issueKey}, which suggests it belongs to another issue`,
    );
  }

  return violations;
}

function checkLabels(payload: TriagePayload): readonly string[] {
  const violations: string[] = [];

  for (const label of payload.mutation.labelsRemove) {
    if (OWNED_LABEL_NAMESPACES.some((namespace) => label.startsWith(namespace))) {
      continue;
    }

    // Not owned outright. It may still be revisable, in which case the question
    // is not "may this be removed" but "is something taking its place" — and the
    // answer has to come from this same mutation, since there is no later edit
    // to rely on. `find` rather than `some`: the namespace is needed to look for
    // the replacement, and to say which one was missing.
    const revisable = REVISABLE_LABEL_NAMESPACES.find((namespace) => label.startsWith(namespace));
    if (revisable === undefined) {
      violations.push(
        `labelsRemove contains "${label}", which is not in a namespace the skill owns — §11 forbids touching a human label`,
      );
      continue;
    }

    if (!payload.mutation.labelsAdd.some((added) => added.startsWith(revisable))) {
      violations.push(
        `labelsRemove contains "${label}" but the mutation adds no other ${revisable} label — §11 allows revising this namespace, not emptying it`,
      );
    }
  }

  // The namespace check above lets any `agent:` label through, which is too
  // generous for this one namespace — see TRIAGE_OWNED_AGENT_LABELS. Both
  // halves of the delta are checked: adding `agent:start` would be the skill
  // authorising its own solve, and removing `agent:solving` would unclaim one
  // already running.
  for (const label of [...payload.mutation.labelsAdd, ...payload.mutation.labelsRemove]) {
    if (label.startsWith("agent:") && !TRIAGE_OWNED_AGENT_LABELS.has(label)) {
      violations.push(
        `the mutation touches "${label}", and triage owns only ${[...TRIAGE_OWNED_AGENT_LABELS].join(", ")} in the agent: namespace — agent:start is a human's authorisation and the rest belong to the solver`,
      );
    }
  }

  // The delta and the verdict's own label list are two renderings of one
  // decision, and they are produced by the same run. Adding a label the verdict
  // never suggested means they have come apart somewhere.
  const suggested = new Set(payload.labels);
  for (const label of payload.mutation.labelsAdd) {
    if (!suggested.has(label)) {
      violations.push(
        `labelsAdd contains "${label}", which is absent from the verdict's own label list — the delta and the verdict disagree`,
      );
    }
  }

  // The SSX-3822 check, at the only level where it can be stated precisely.
  //
  // An earlier version of this read the comment PROSE for the string
  // "dor:pass". It was withdrawn after it refused the correction to SSX-3822
  // itself: a send-back that removes a wrongly-applied `dor:pass` has to name
  // the label in order to repudiate it, and in the LABEL DELTA it renders it a
  // second time. Substring matching cannot distinguish asserting a pass from
  // reversing one, so the check fired hardest on exactly the runs worth most —
  // the ones cleaning up after a bad run.
  //
  // Applying the label is an assertion; mentioning it is not. So the delta is
  // the thing to read. `assertDorCoherent` covers the same contradiction via
  // `labels` and the verdict; this catches the case where those two are honest
  // and only the delta claims the pass.
  if (payload.dorPlaceholders.length > 0 && payload.mutation.labelsAdd.includes("dor:pass")) {
    violations.push(
      `labelsAdd applies dor:pass while the ticket still contains ${payload.dorPlaceholders
        .map((placeholder) => `"${placeholder}"`)
        .join(
          ", ",
        )} — DOR_CHECKLIST.md allows dor:pass "only if 1-9 hold", and row 9 is the baseline metric`,
    );
  }

  return violations;
}

/**
 * The fitness call has to agree with the rest of the payload that produced it.
 *
 * Same shape of rule as everything else here, for the same reason: this cannot
 * tell you the analyst was wrong about whether a bot could fix the ticket. It
 * can only tell you the payload contradicts itself, which — twice now, on
 * SSX-3814 and SSX-3822 — is what a wrong answer has actually looked like.
 *
 * The verdict coupling is the load-bearing rule, and it is not an extra
 * restriction invented here. It falls out of three existing ones meeting:
 *
 *   - `assertDorCoherent` already forbids `ready-ish` while placeholders remain,
 *     so `ready-ish` implies the Definition of Ready held.
 *   - DoR holding implies acceptance criteria concrete enough to test against,
 *     which is precisely what an unattended fixer needs and cannot invent.
 *   - The skill's dev lens — repo, blast radius, the file, the technique, the
 *     rejected alternative — is only emitted on ACCEPT, and it is most of the
 *     evidence a fitness call rests on.
 *
 * So a `dor:gaps` ticket is never agent-solvable. That reads like a limitation
 * and is closer to the opposite: it is the same fact stated three ways, and the
 * gate only has to check the cheapest of them. Note that the placeholder case
 * needs no rule of its own — `assertDorCoherent` throws before this runs.
 *
 * The label rule reads `labels`, never `labelsAdd`, and that distinction was
 * bought the hard way. `labelsAdd` is a delta holding only labels not already on
 * the issue, so on the second run over a ticket already marked solvable the
 * label is legitimately absent from it. A gate keyed on the delta would fire on
 * exactly the re-runs it should stay quiet for — the same false-positive shape
 * that got the old prose check withdrawn. `labels` is the full set the verdict
 * asserts, so it is the honest place to look for an assertion.
 */
function checkAgentFitness(payload: TriagePayload): readonly string[] {
  const fitness = payload.agentFitness;
  const violations: string[] = [];
  const labelled = payload.labels.includes("agent:solvable");

  if (fitness.solvable && payload.verdict !== "ready-ish") {
    violations.push(
      `agentFitness.solvable is true while the verdict is "${payload.verdict}" — only a ready-ish ticket has passed DoR, and without that there are no acceptance criteria for an agent to verify its own fix against`,
    );
  }

  if (fitness.solvable && fitness.blockers.length > 0) {
    violations.push(
      `agentFitness.solvable is true while still listing ${fitness.blockers
        .map((blocker) => `"${blocker}"`)
        .join(
          ", ",
        )} as a blocker — if the blocker is real the ticket is not solvable, and if it is not it should not be listed`,
    );
  }

  if (fitness.solvable && fitness.repo.trim() === "") {
    violations.push(
      `agentFitness.solvable is true but names no repo — nothing downstream could check it against the allowlist, so there is nowhere to send the fix`,
    );
  }

  // Both directions. The field is what a solver reads and the label is what a
  // human reads, and the whole defect class this gate exists for is those two
  // disagreeing while each looks reasonable alone.
  if (fitness.solvable && !labelled) {
    violations.push(
      `agentFitness.solvable is true but the verdict's labels omit "agent:solvable" — the assessment would never reach the board`,
    );
  }

  if (!fitness.solvable && labelled) {
    violations.push(
      `the verdict's labels include "agent:solvable" while agentFitness.solvable is false — the label would authorise work the assessment declined`,
    );
  }

  violations.push(...checkPlausible(payload));

  return violations;
}

/**
 * The two rules that keep `plausible` from becoming a second `solvable`.
 *
 * Separated from the block above because they guard a different cost. Every
 * rule up there protects against a bot editing source; these protect against a
 * ticket joining a list that buys a paid triage run every time somebody touches
 * it. Both are worth refusing a post over, and they are not the same risk, so
 * they are not the same paragraph.
 *
 * **Mutually exclusive, and stated as a rule rather than left to the model.**
 * `plausible` means "not solvable *yet*", so a payload asserting both is not a
 * strong opinion, it is two answers. Left unchecked, the field with the weaker
 * consequence would drift into being a hedged version of the field with the
 * stronger one, and the first time that mattered would be a ticket both queued
 * for a solve and subscribed to a watch.
 *
 * **A watch needs a condition that can end it.** `plausible` with no blockers
 * says the ticket is nearly solvable and cannot say what is missing. There is
 * nothing a reporter could do to clear it, so it is a subscription with no
 * unsubscribe — the ticket is re-triaged on every edit until a bound fires,
 * having never been actionable. The `blockers` list is not an explanation here,
 * it is the exit condition.
 *
 * The label mirror is the same both-directions check `solvable` gets and for the
 * same reason: the field is what the watcher reads and the label is what a human
 * reads and what the query selects on. `plausible` without the label is an
 * assessment that never reaches the board; the label without the field is a
 * standing charge nothing asked for.
 *
 * **One case this cannot check, and it is the one to remember.** A ticket
 * already carrying `agent:watching` that is re-triaged into `plausible: false`
 * needs the label *removed*, and the payload has no idea what is on the board —
 * `TriagePayload` carries what the verdict asserts, never the live label set. So
 * the rule below catches "asserting a watch while declining one" and cannot
 * catch "declining a watch that is already running". Ending an existing watch is
 * the watcher's job, and it is the reason the watch needs a terminal of its own
 * rather than trusting the next triage to tidy up after it.
 */
function checkPlausible(payload: TriagePayload): readonly string[] {
  const fitness = payload.agentFitness;
  const violations: string[] = [];
  const labelled = payload.labels.includes(AGENT_LABELS.watching);

  if (fitness.plausible && fitness.solvable) {
    violations.push(
      `agentFitness.plausible and agentFitness.solvable are both true — plausible means "not solvable yet", so the two are alternatives and a payload asserting both has not made the call`,
    );
  }

  if (fitness.plausible && fitness.blockers.length === 0) {
    violations.push(
      `agentFitness.plausible is true but blockers is empty — the blockers are what a reporter fills in to end the watch, so without them the ticket would be re-triaged on every edit with no condition that could ever clear it`,
    );
  }

  if (fitness.plausible && !labelled) {
    violations.push(
      `agentFitness.plausible is true but the verdict's labels omit "${AGENT_LABELS.watching}" — nothing would subscribe to the ticket, so the assessment would never reach the board`,
    );
  }

  if (!fitness.plausible && labelled) {
    violations.push(
      `the verdict's labels include "${AGENT_LABELS.watching}" while agentFitness.plausible is false — the label would put the ticket on a paid watch list the assessment did not ask for`,
    );
  }

  return violations;
}

function checkComponent(mutation: Mutation): readonly string[] {
  if (mutation.component === "" || POLICY_STREAMS.has(mutation.component)) {
    return [];
  }
  return [
    `component "${mutation.component}" is not one of the four policy streams (${[...POLICY_STREAMS].join(", ")})`,
  ];
}
