/**
 * The check that stands between deciding and posting: the analyst returns a mutation instead of
 * performing it, and refusing here means nothing was sent. Collects every violation rather than
 * the first, and checks only mechanical rules — it can say a verdict contradicts itself, never
 * that it is wrong.
 */

import { AGENT_LABELS } from "../solve/labels.ts";
import {
  type Mutation,
  TriageError,
  type TriagePayload,
  UNATTRIBUTED_DOR_ROW,
  assertDorCoherent,
  blockingPlaceholders,
} from "./runner.ts";

/**
 * The §11 idempotency sentinel, verbatim: the skill recognises its own prior comment by this
 * exact line, so a body omitting it can be posted but never updated in place.
 */
export const FOOTER_SENTINEL = "_🤖 Generated by intake-triage · re-run the command to refresh._";

/**
 * The line that opens the agent-fitness block, and the marker that makes it strippable. A prefix
 * rather than a whole line, since what follows varies with verdict/repo/confidence and a model
 * paraphrasing the block; matching to the end of "fitness" catches both.
 */
export const FITNESS_MARKER = "🤖 **Agent fitness";

/** The only components §11 permits the skill to set. Cap of one. */
export const POLICY_STREAMS: ReadonlySet<string> = new Set([
  "SSX Advisor",
  "EDH",
  "SSX Partner",
  "SSX Nettsalg",
]);

/**
 * Label namespaces the skill owns and may remove, per §11: "remove ONLY the skill's own stale
 * namespaced labels; never touch a human label." Must match §11 exactly, not a superset — widen
 * this only by widening §11 first.
 */
const OWNED_LABEL_NAMESPACES: readonly string[] = [
  "route:",
  "dup:",
  "dor:",
  "tier:",
  "intake:",
  "next:",
  "agent:",
];

/**
 * Namespaces the skill also writes, removable only as half of a swap: permitted only when the
 * same mutation adds at least one label in the same namespace, never a bare deletion, since a
 * fact removed (e.g. `svc:`) is a hole no later re-triage would notice.
 *
 * "At least one", not "exactly one", because `team:` is legitimately multi-valued on dual-owned
 * repos. `impl-uncertain` stays unremovable — it's a bare label with no namespace to swap within.
 */
const REVISABLE_LABEL_NAMESPACES: readonly string[] = [
  "team:",
  "jira:",
  "domain:",
  "svc:",
  "value:",
  "effort:",
];

/**
 * The only `agent:` labels triage may touch. `agent:start` (human authorisation) and the solver's
 * own lifecycle labels are excluded deliberately: a Jira ticket is data a model reads, not an
 * instruction, so triage must not be able to grant itself authorisation a ticket body could ask
 * for. `agent:watching` is triage's own assessment too and must stay removable by a later triage.
 */
const TRIAGE_OWNED_AGENT_LABELS: ReadonlySet<string> = new Set([
  AGENT_LABELS.solvable,
  AGENT_LABELS.watching,
]);

/** The mutation may not be posted. Carries every reason, not the first. */
export class UnpostableError extends TriageError {
  readonly issueKey: string;
  readonly violations: readonly string[];

  constructor(issueKey: string, violations: readonly string[]) {
    super(
      `${issueKey}: refusing to post — ${String(violations.length)} problem(s) with the mutation:\n` +
        violations.map((violation) => `  - ${violation}`).join("\n"),
    );
    this.name = "UnpostableError";
    this.issueKey = issueKey;
    this.violations = violations;
  }
}

/**
 * Throws unless every mechanical rule holds. Re-runs `assertDorCoherent` even though
 * `parsePayload` already did, so a future caller building a payload another way still gets it.
 */
export function assertPostable(payload: TriagePayload, issueKey: string): void {
  assertDorCoherent(payload, issueKey);

  const violations = [
    ...checkComment(payload, issueKey),
    ...checkLabels(payload),
    ...checkComponent(payload.mutation),
    ...checkAgentFitness(payload),
  ];

  if (violations.length > 0) {
    throw new UnpostableError(issueKey, violations);
  }
}

function checkComment(payload: TriagePayload, issueKey: string): readonly string[] {
  const body = payload.mutation.commentBody;
  const violations: string[] = [];

  if (body.trim() === "") {
    // Follow-on complaints would only bury the one that matters.
    return ["the comment body is empty, so there is nothing to post"];
  }

  if (!body.trimEnd().endsWith(FOOTER_SENTINEL)) {
    violations.push(
      `the comment body does not end with the §11 footer sentinel, so a re-run could not update it in place and would post a second copy instead`,
    );
  }

  const markers = body.split("\n").filter((line) => line.startsWith(FITNESS_MARKER)).length;
  if (markers > 1) {
    // Reaching here means `withFitnessNote`'s strip missed a paraphrase of the marker it keys on.
    violations.push(
      `the comment body carries ${markers} agent-fitness blocks, so two accounts of the same call would be posted at once`,
    );
  }

  if (!body.includes(issueKey)) {
    // The poster is given a body it did not write; this is the one place body-to-key pairing is checked.
    violations.push(
      `the comment body never mentions ${issueKey}, which suggests it belongs to another issue`,
    );
  }

  return violations;
}

function checkLabels(payload: TriagePayload): readonly string[] {
  const violations: string[] = [];

  for (const label of payload.mutation.labelsRemove) {
    if (OWNED_LABEL_NAMESPACES.some((namespace) => label.startsWith(namespace))) {
      continue;
    }

    // `find` rather than `some`: the matched namespace is needed to look for the replacement.
    const revisable = REVISABLE_LABEL_NAMESPACES.find((namespace) => label.startsWith(namespace));
    if (revisable === undefined) {
      violations.push(
        `labelsRemove contains "${label}", which is not in a namespace the skill owns — §11 forbids touching a human label`,
      );
      continue;
    }

    if (!payload.mutation.labelsAdd.some((added) => added.startsWith(revisable))) {
      violations.push(
        `labelsRemove contains "${label}" but the mutation adds no other ${revisable} label — §11 allows revising this namespace, not emptying it`,
      );
    }
  }

  // The namespace check above lets any `agent:` label through; this narrows to TRIAGE_OWNED_AGENT_LABELS.
  for (const label of [...payload.mutation.labelsAdd, ...payload.mutation.labelsRemove]) {
    if (label.startsWith("agent:") && !TRIAGE_OWNED_AGENT_LABELS.has(label)) {
      violations.push(
        `the mutation touches "${label}", and triage owns only ${[...TRIAGE_OWNED_AGENT_LABELS].join(", ")} in the agent: namespace — agent:start is a human's authorisation and the rest belong to the solver`,
      );
    }
  }

  // The delta and the verdict's label list are two renderings of one decision from the same run.
  const suggested = new Set(payload.labels);
  for (const label of payload.mutation.labelsAdd) {
    if (!suggested.has(label)) {
      violations.push(
        `labelsAdd contains "${label}", which is absent from the verdict's own label list — the delta and the verdict disagree`,
      );
    }
  }

  // Reads the label DELTA, not the comment prose: applying `dor:pass` is an assertion, mentioning
  // it is not. Only blocking rows count — rows 8-9 are advisory, so a placeholder there is a nudge
  // the report carries, not a claim the delta contradicts.
  const blocking = blockingPlaceholders(payload.dorPlaceholders);
  if (blocking.length > 0 && payload.mutation.labelsAdd.includes("dor:pass")) {
    violations.push(
      `labelsAdd applies dor:pass while the ticket still contains ${blocking
        .map(
          (placeholder) =>
            `"${placeholder.text}" (${
              placeholder.row === UNATTRIBUTED_DOR_ROW ? "no row given" : `row ${placeholder.row}`
            })`,
        )
        .join(
          ", ",
        )} — DOR_CHECKLIST.md allows dor:pass "only if 1-7 hold", and those rows are blocking`,
    );
  }

  return violations;
}

/**
 * `.claude/skills/intake-triage/INTAKE_INSTRUCTIONS.md` §11's delta legitimately omits a label
 * already on the issue, so an owned label present in `labels` but missing from `labelsAdd` is not
 * on its own a defect — except on a `"create"` run, where nothing already wrote the label:
 * `checkLabels` above restricts every other writer out of the `agent:` namespace, so
 * `commentAction: "create"` (no prior triage comment matched) means the label cannot already be on
 * the issue. On that shape the omission is the two fields of one payload disagreeing, and the label
 * would reach the comment body but never the board.
 */
function checkOwnedLabelReachesDelta(payload: TriagePayload, label: string): readonly string[] {
  if (payload.mutation.commentAction !== "create") {
    return [];
  }

  if (payload.labels.includes(label) && !payload.mutation.labelsAdd.includes(label)) {
    return [
      `the verdict's labels include "${label}" but labelsAdd omits it, and commentAction is "create" — with no prior triage comment there is nothing already on the issue to excuse the omission`,
    ];
  }

  return [];
}

/**
 * The fitness call has to agree with the rest of the payload: only `ready-ish` has passed DoR, so
 * a `dor:gaps` ticket is never agent-solvable (this falls out of `assertDorCoherent` plus the
 * skill's dev-lens evidence being ACCEPT-only, not a rule invented here).
 *
 * The label checks below read `labels`, never `labelsAdd` — `labelsAdd` is a delta that
 * legitimately omits a label already on the issue from a re-triage, so keying on it would
 * false-positive on exactly those re-runs. `checkOwnedLabelReachesDelta` is the exception, for the
 * one run shape where that allowance cannot apply.
 */
function checkAgentFitness(payload: TriagePayload): readonly string[] {
  const fitness = payload.agentFitness;
  const violations: string[] = [];
  const labelled = payload.labels.includes(AGENT_LABELS.solvable);

  if (fitness.solvable && payload.verdict !== "ready-ish") {
    violations.push(
      `agentFitness.solvable is true while the verdict is "${payload.verdict}" — only a ready-ish ticket has passed DoR, and without that there are no acceptance criteria for an agent to verify its own fix against`,
    );
  }

  if (fitness.solvable && fitness.blockers.length > 0) {
    violations.push(
      `agentFitness.solvable is true while still listing ${fitness.blockers
        .map((blocker) => `"${blocker}"`)
        .join(
          ", ",
        )} as a blocker — if the blocker is real the ticket is not solvable, and if it is not it should not be listed`,
    );
  }

  if (fitness.solvable && fitness.repo.trim() === "") {
    violations.push(
      `agentFitness.solvable is true but names no repo — nothing downstream could check it against the allowlist, so there is nowhere to send the fix`,
    );
  }

  // Both directions: the field is what a solver reads, the label is what a human reads.
  if (fitness.solvable && !labelled) {
    violations.push(
      `agentFitness.solvable is true but the verdict's labels omit "agent:solvable" — the assessment would never reach the board`,
    );
  }

  if (!fitness.solvable && labelled) {
    violations.push(
      `the verdict's labels include "agent:solvable" while agentFitness.solvable is false — the label would authorise work the assessment declined`,
    );
  }

  violations.push(...checkOwnedLabelReachesDelta(payload, AGENT_LABELS.solvable));
  violations.push(...checkPlausible(payload));

  return violations;
}

/**
 * Keeps `plausible` from becoming a second `solvable`: the two are mutually exclusive (asserting
 * both is two answers, not one), and a `plausible` watch must carry blockers, since they're the
 * exit condition, not an explanation.
 *
 * Cannot catch a ticket already on the board with `agent:watching` being re-triaged to
 * `plausible: false` — `TriagePayload` carries only what this run asserts, never the live label
 * set, so ending an existing watch is the watcher's job, not this gate's.
 */
function checkPlausible(payload: TriagePayload): readonly string[] {
  const fitness = payload.agentFitness;
  const violations: string[] = [];
  const labelled = payload.labels.includes(AGENT_LABELS.watching);

  if (fitness.plausible && fitness.solvable) {
    violations.push(
      `agentFitness.plausible and agentFitness.solvable are both true — plausible means "not solvable yet", so the two are alternatives and a payload asserting both has not made the call`,
    );
  }

  if (fitness.plausible && fitness.blockers.length === 0) {
    violations.push(
      `agentFitness.plausible is true but blockers is empty — the blockers are what a reporter fills in to end the watch, so without them the ticket would be re-triaged on every edit with no condition that could ever clear it`,
    );
  }

  if (fitness.plausible && !labelled) {
    violations.push(
      `agentFitness.plausible is true but the verdict's labels omit "${AGENT_LABELS.watching}" — nothing would subscribe to the ticket, so the assessment would never reach the board`,
    );
  }

  if (!fitness.plausible && labelled) {
    violations.push(
      `the verdict's labels include "${AGENT_LABELS.watching}" while agentFitness.plausible is false — the label would put the ticket on a paid watch list the assessment did not ask for`,
    );
  }

  violations.push(...checkOwnedLabelReachesDelta(payload, AGENT_LABELS.watching));

  return violations;
}

function checkComponent(mutation: Mutation): readonly string[] {
  if (mutation.component === "" || POLICY_STREAMS.has(mutation.component)) {
    return [];
  }
  return [
    `component "${mutation.component}" is not one of the four policy streams (${[...POLICY_STREAMS].join(", ")})`,
  ];
}
