import { describe, expect, it, vi } from "vitest";

import { ALLOWED_TOOLS, type Mutation } from "./runner.ts";

// Stubs the subprocess, so nothing here can reach storecode or Jira.

const runSession = vi.hoisted(() => vi.fn());
vi.mock("./session.ts", async (importOriginal) => ({
  ...(await importOriginal<typeof import("./session.ts")>()),
  runSession,
}));

const { POSTER_TOOLS, PostError, buildPostArgs, buildPostPrompt, parseReceipt, runPost } =
  await import("./poster.ts");
type PostOptions = import("./poster.ts").PostOptions;

const BODY = "## Triage of SSX-1234\n\nVerdict: needs-info.\n\n_🤖 Generated by intake-triage._";

function mutation(overrides: Partial<Mutation> = {}): Mutation {
  return {
    commentBody: BODY,
    labelsAdd: [],
    labelsRemove: [],
    component: "",
    links: [],
    commentAction: "create",
    ...overrides,
  };
}

function options(overrides: Partial<Mutation> = {}): PostOptions {
  return {
    issueKey: "SSX-1234",
    mutation: mutation(overrides),
    executable: "storecode",
    workingDirectory: "/tmp",
    timeoutMs: 1000,
  };
}

/** A clean receipt, as the stubbed subprocess would return it. */
function receipt(overrides: Record<string, unknown> = {}) {
  return {
    commentAction: "created",
    labelsWritten: [],
    linksCreated: [],
    problems: [],
    ...overrides,
  };
}

describe("POSTER_TOOLS", () => {
  it("never grants the transition tool", () => {
    // The skill promises never to change status — "not after a `y`, not for a
    // close-as-duplicate". Withholding the tool makes that enforceable rather
    // than merely promised.
    expect(POSTER_TOOLS.join(" ")).not.toContain("transitionJiraIssue");
  });

  it("grants the three §11 write tools", () => {
    for (const tool of ["editJiraIssue", "addCommentToJiraIssue", "createIssueLink"]) {
      expect(POSTER_TOOLS.join(" ")).toContain(tool);
    }
  });

  it("grants the reads that §11 requires the write to be based on", () => {
    // Not blind: the label write must union against what is live, and the
    // comment must update in place when one matching the sentinel and its own
    // authorship exists. Both are reads.
    expect(POSTER_TOOLS).toContain("mcp__atlassian__getJiraIssue");
    expect(POSTER_TOOLS).toContain("mcp__atlassian__atlassianUserInfo");
  });

  it("grants nothing it could form a second opinion with", () => {
    // This is the property that makes the poster a transcriber rather than a
    // second analyst. No vault, no Confluence, no duplicate hunt.
    for (const tool of ["search", "Confluence", "Read", "Grep", "Glob"]) {
      expect(POSTER_TOOLS.join(" ")).not.toContain(tool);
    }
  });

  it("is a strict subset of nothing the analyst needs to think", () => {
    // Sanity-check the two allowlists have genuinely diverged: the analyst's
    // research tools must not have leaked into the writer's.
    const research = ALLOWED_TOOLS.filter((tool) => tool.includes("search") || tool === "Read");

    for (const tool of research) {
      expect(POSTER_TOOLS).not.toContain(tool);
    }
  });
});

describe("buildPostPrompt", () => {
  it("carries the comment body verbatim", () => {
    expect(buildPostPrompt(options())).toContain(BODY);
  });

  it("delimits the body, so its markdown cannot be mistaken for instructions", () => {
    const prompt = buildPostPrompt(options());
    const start = prompt.indexOf("---BEGIN COMMENT BODY---");
    const end = prompt.indexOf("---END COMMENT BODY---");

    expect(start).toBeGreaterThan(-1);
    expect(end).toBeGreaterThan(start);
    expect(prompt.slice(start, end)).toContain(BODY);
  });

  it("never invokes the skill, which would re-run the analysis", () => {
    // The whole point of the split. A slash command here would pay for the
    // grooming twice and post a verdict nobody checked.
    const prompt = buildPostPrompt(options());

    expect(prompt).not.toContain("/intake-triage");
    expect(prompt).not.toContain("--yes");
  });

  it("tells it not to re-analyse, and not to reword", () => {
    const prompt = buildPostPrompt(options());

    expect(prompt).toContain("Do NOT re-analyse");
    expect(prompt).toContain("VERBATIM");
  });

  it("forbids a transition in the prompt as well as in the allowlist", () => {
    expect(buildPostPrompt(options())).toContain("Never change the issue status");
  });

  it("asks for an update when a prior comment exists", () => {
    const prompt = buildPostPrompt(options({ commentAction: "update" }));

    expect(prompt).toContain("UPDATE the existing intake-triage comment in place");
  });

  it("asks for a create otherwise, but still has it check first", () => {
    // Belt and braces: the analyst decided create from what it saw a minute
    // ago, and a duplicate comment is the failure this sentinel exists to stop.
    const prompt = buildPostPrompt(options({ commentAction: "create" }));

    expect(prompt).toContain("CREATE a new comment");
    expect(prompt).toContain("update that one instead");
  });

  it("spells out the union rule when there are labels to change", () => {
    const prompt = buildPostPrompt(
      options({ labelsAdd: ["dor:gaps"], labelsRemove: ["dor:pass"] }),
    );

    expect(prompt).toContain("dor:gaps");
    expect(prompt).toContain("dor:pass");
    expect(prompt).toContain("Never send a bare replacement array");
  });

  it("tells it to leave labels alone when there are none to change", () => {
    // Otherwise it has a tool, an issue and no instruction — which is an
    // invitation to tidy up.
    const prompt = buildPostPrompt(options());

    expect(prompt).toContain("no change required. Do not call editJiraIssue");
  });

  it("names the component only when one was detected", () => {
    expect(buildPostPrompt(options({ component: "SSX Advisor" }))).toContain('"SSX Advisor"');
    expect(buildPostPrompt(options({ component: "" }))).toContain("COMPONENT — no change required");
  });

  it("lists links exactly, and says no others", () => {
    const prompt = buildPostPrompt(
      options({ links: [{ type: "duplicates", targetKey: "SSX-9999" }] }),
    );

    expect(prompt).toContain("duplicates → SSX-9999");
    expect(prompt).toContain("and no others");
  });

  it("says there are none when there are none", () => {
    expect(buildPostPrompt(options())).toContain("LINKS — none to create");
  });
});

describe("buildPostArgs", () => {
  it("uses the same non-interactive shape as the analyst", () => {
    const args = buildPostArgs(options());

    expect(args[args.indexOf("--output-format") + 1]).toBe("stream-json");
    expect(args).toContain("--verbose");
    expect(args[args.indexOf("--permission-mode") + 1]).toBe("dontAsk");
  });

  it("passes the poster allowlist, not the analyst's", () => {
    const args = buildPostArgs(options());

    expect(args[args.indexOf("--allowedTools") + 1]).toBe(POSTER_TOOLS.join(","));
  });

  it("gives it no extra working directory", () => {
    // The vault is the analyst's business. The poster has nothing to look up.
    expect(buildPostArgs(options())).not.toContain("--add-dir");
  });

  it("passes a parseable schema inline", () => {
    const args = buildPostArgs(options());

    expect(() => JSON.parse(args[args.indexOf("--json-schema") + 1] ?? "")).not.toThrow();
  });
});

describe("parseReceipt", () => {
  it("reads a full receipt", () => {
    expect(
      parseReceipt(
        {
          commentAction: "updated",
          labelsWritten: ["dor:gaps", "blocked"],
          linksCreated: ["relates to SSX-9"],
          problems: [],
        },
        "SSX-1234",
      ),
    ).toEqual({
      commentAction: "updated",
      labelsWritten: ["dor:gaps", "blocked"],
      linksCreated: ["relates to SSX-9"],
      problems: [],
    });
  });

  it.each([undefined, null, "created", 42])("refuses non-object output %o", (value) => {
    expect(() => parseReceipt(value, "SSX-1234")).toThrow(/No structured output/);
  });

  it("treats an unrecognised action as skipped, not as success", () => {
    // Failing closed: an action we cannot read is not evidence the write landed.
    expect(parseReceipt({ commentAction: "maybe?" }, "SSX-1").commentAction).toBe("skipped");
  });

  it("defaults the arrays rather than crashing on a partial receipt", () => {
    expect(parseReceipt({ commentAction: "created" }, "SSX-1")).toEqual({
      commentAction: "created",
      labelsWritten: [],
      linksCreated: [],
      problems: [],
    });
  });
});

describe("runPost", () => {
  it("returns the receipt on a clean write", async () => {
    runSession.mockResolvedValueOnce(receipt({ commentAction: "updated" }));

    await expect(runPost(options())).resolves.toMatchObject({ commentAction: "updated" });
  });

  it("throws when the poster reports it did not post the comment", async () => {
    // The one outcome that must not pass silently: a run that succeeded
    // mechanically while doing nothing. Throwing sends the poller round again.
    runSession.mockResolvedValueOnce(receipt({ commentAction: "skipped" }));

    await expect(runPost(options())).rejects.toThrow(PostError);
  });

  it("names the problems in that error, so the log explains itself", async () => {
    runSession.mockResolvedValueOnce(
      receipt({ commentAction: "skipped", problems: ["addCommentToJiraIssue was denied"] }),
    );

    await expect(runPost(options())).rejects.toThrow(/addCommentToJiraIssue was denied/);
  });

  it("says so plainly when it skipped and offered no reason", async () => {
    runSession.mockResolvedValueOnce(receipt({ commentAction: "skipped" }));

    await expect(runPost(options())).rejects.toThrow(/none reported/);
  });

  it("does NOT throw on a partial success, because the writes already landed", async () => {
    // Failing the ticket here would send the poller round to redo work that
    // partly succeeded. The comment is on the issue; the problem is logged.
    runSession.mockResolvedValueOnce(
      receipt({ commentAction: "created", problems: ["component was rejected by Jira"] }),
    );

    await expect(runPost(options())).resolves.toMatchObject({
      problems: ["component was rejected by Jira"],
    });
  });

  it("requires a live Atlassian session", async () => {
    runSession.mockResolvedValueOnce(receipt());
    await runPost(options());

    expect(runSession.mock.calls[0]?.[0]).toMatchObject({ requiredMcpServers: ["atlassian"] });
  });

  it("withholds the Jira REST credential from the write subprocess too", async () => {
    // The discovery/grooming split holds on both sides: every mutation is made
    // by the MCP session's own Jira user, never by the polling credential.
    runSession.mockResolvedValueOnce(receipt());
    await runPost(options());

    expect(runSession.mock.calls[0]?.[0]?.env).not.toHaveProperty("JIRA_AUTH");
  });
});
