/**
 * Structured-output contract for a triage run. Passed to Claude Code via `--json-schema`, which
 * takes inline JSON, not a path. Kept deliberately small: a reply that fails validation eventually
 * gives up with `error_max_structured_output_retries`, so every extra required field is another
 * way for a run to fail after paying for the work.
 */

export const TRIAGE_SCHEMA = {
  $schema: "http://json-schema.org/draft-07/schema#",
  type: "object",
  additionalProperties: false,
  required: ["verdict", "labels", "dorPlaceholders", "recommendedNextStep", "report", "mutation"],
  properties: {
    verdict: {
      type: "string",
      enum: ["duplicate", "not-our-team", "out-of-scope", "needs-info", "ready-ish"],
      // Mapping spelled out here rather than left to be guessed from the skill's own banners.
      // `out-of-scope` is needed: without it a model picks `needs-info` as "closest".
      description:
        'The verdict, taken from the report banner. "ACCEPT" is ready-ish. "REJECT → duplicate" (or possible duplicate) is duplicate. "REJECT → out-of-scope" is out-of-scope. "ROUTE" is not-our-team. "SEND BACK" is needs-info.',
    },
    labels: {
      type: "array",
      items: { type: "string" },
      description:
        "Suggested Jira labels, e.g. dup:open, dup:solved, dor:gaps, dor:pass, route:ours, route:other-team.",
    },
    dorPlaceholders: {
      type: "array",
      // Doubles as an instruction: the model reads this description, so stating the rule here is
      // the cheapest place to state it. The row number lets an unattributed placeholder be told
      // apart from a nudge, now that rows 8 and 9 are advisory and can no longer block on their own.
      items: {
        type: "object",
        additionalProperties: false,
        required: ["text", "row"],
        properties: {
          text: {
            type: "string",
            description:
              'The placeholder verbatim, exactly as it appears in the ticket — e.g. "[N]", "[TBD]", "<beløp>".',
          },
          row: {
            type: "integer",
            minimum: 1,
            maximum: 10,
            description:
              "Which DoR checklist row this placeholder stands in for: the row that would hold if somebody filled it in. Judge from what the placeholder is standing in for and the section it sits in — a placeholder inside an acceptance criterion is row 3, an unfilled baseline metric is row 9, an unnamed segment is row 1. Answer honestly and specifically; do not default to a blocking row to be safe, and do not default to 9 to avoid one.",
          },
        },
      },
      description:
        'Literal unfilled fill-in placeholders still present in the ticket body, each with the DoR row it stands in for. Empty array if there are none. Rows 1-3 (problem/segment, value and why-now, acceptance criteria) are BLOCKING: a placeholder attributed to one of them means that row does not hold, which requires `dor:gaps` rather than `dor:pass` and rules out the "ready-ish" verdict. Rows 8 and 9 (size, evidence/data) are ADVISORY and block nothing — report the placeholder, and still emit `dor:pass` if rows 1-7 hold.',
    },
    recommendedNextStep: {
      type: "string",
      description: "One sentence: what a human should do with this issue next.",
    },
    report: {
      type: "string",
      description: "The full triage report as markdown, in the language of the source ticket.",
    },
    mutation: {
      type: "object",
      additionalProperties: false,
      required: ["commentBody", "labelsAdd", "labelsRemove", "component", "links", "commentAction"],
      // The §11 payload preview, returned as data instead of only printed, so the verdict can be
      // checked before anything reaches the ticket.
      description:
        "The exact §11 mutation payload — what a confirmed write WOULD send. Fill this in fully even on a --no-write run: it is the payload preview, rendered as data. It is never posted by this run.",
      properties: {
        commentBody: {
          type: "string",
          // §11 suppresses the DoR send-back reporter note in preview; here the field IS the
          // confirmed payload, so that suppression is overridden explicitly below.
          description:
            "The VERBATIM comment body to post, exactly as §11 would render it on a confirmed write. Must end with the footer sentinel line `_🤖 Generated by intake-triage · re-run the command to refresh._` and include the glyph + CONF legend. IMPORTANT: include the DoR send-back reporter note when the verdict warrants one — §11 suppresses that note in preview, but this field is the confirmed payload rather than a preview, and a send-back posted without its reporter note tells the reporter nothing.",
        },
        labelsAdd: {
          type: "array",
          items: { type: "string" },
          description:
            "The `+ add:` half of the §11 LABEL DELTA — only labels not already on the issue.",
        },
        labelsRemove: {
          type: "array",
          items: { type: "string" },
          // Kept in step with §11 by hand; `agent:` is the namespace where an omission would cost
          // most, since the rest of it belongs to a human and to the solver.
          description:
            "The `- remove:` half of the LABEL DELTA. ONLY the skill's own stale namespaced labels (route:*, dup:*, dor:*, tier:*, intake:*, next:*, and agent:solvable). Never a human label, and never any other agent:* label — agent:start is a human's authorisation for a bot to attempt a fix, and agent:solving / agent:done / agent:failed are that bot's own lifecycle.",
        },
        component: {
          type: "string",
          description:
            "The single detected policy stream to apply (SSX Advisor, EDH, SSX Partner or SSX Nettsalg), or an empty string when uncertain or already correct.",
        },
        links: {
          type: "array",
          description:
            "Issue links to create. `duplicates` only for a dup:HIGH confirmed duplicate; `relates to` otherwise.",
          items: {
            type: "object",
            additionalProperties: false,
            required: ["type", "targetKey"],
            properties: {
              type: { type: "string", enum: ["duplicates", "relates to"] },
              targetKey: { type: "string", description: "e.g. SSX-1234" },
            },
          },
        },
        commentAction: {
          type: "string",
          enum: ["create", "update"],
          description:
            "Whether a comment satisfying BOTH the skill's own Jira account authorship AND the full footer sentinel already exists (update) or not (create).",
        },
      },
    },
    agentFitness: {
      type: "object",
      additionalProperties: false,
      // `plausible` is deliberately absent from this list: requiring it would make the next run of
      // an unchanged skill fail its own schema. Its omission reads as `false`, same as the whole
      // object's omission, so nothing is lost by asking rather than requiring.
      required: ["solvable", "confidence", "repo", "rationale", "blockers"],
      // Deliberately absent from the top-level `required` list: `parseAgentFitness` reads a
      // missing object as `solvable: false`, so a field that grants privilege fails closed rather
      // than turning a model's silence into a retry loop.
      description:
        "Whether an autonomous coding agent could safely and reliably fix this ticket without a human writing the patch. Judge conservatively: this drives whether a bot is later allowed to edit source and open a pull request, so the cost of a wrong `true` is far higher than the cost of a wrong `false`. Omit this object entirely if you are unsure — omission is read as `solvable: false`.",
      properties: {
        solvable: {
          type: "boolean",
          // The verdict coupling is stated here as well as enforced in the gate: a model told the
          // rule up front produces a coherent payload rather than a retry.
          description:
            'True ONLY if ALL of: the verdict is "ready-ish"; the fault is localised to one repo you can name; the acceptance criteria are concrete enough that a passing test could demonstrate the fix; and the change does not need a product decision, a design, a schema/API migration, or credentials. A missing size estimate (DoR row 8) or a missing baseline metric (row 9) is NOT a reason to say false — those rows are advisory and describe measurement, not fixability. If the verdict is anything other than "ready-ish", this MUST be false — a ticket that does not meet Definition of Ready has nothing an agent could verify itself against. When true, you MUST also include the label "agent:solvable" in the top-level `labels` array. NEVER emit any other `agent:*` label: "agent:start" in particular is a human authorisation and is not yours to grant.',
        },
        plausible: {
          type: "boolean",
          // Deliberately the narrow half of a send-back, not a second opinion about it:
          // `needs-info` is far too broad to subscribe to, since every re-look is a paid run.
          description:
            'True if this ticket is NOT solvable today but WOULD BE if the items you list in `blockers` were filled in by the reporter. This is the narrow case: a send-back with a concrete, fillable gap — missing reproduction steps, an unspecified expected value, an acceptance criterion nobody has made testable — and nothing else standing in the way. It is NOT "this might be automatable one day". If the ticket would still need a product decision, a design, a migration, or work in more than one repository once the blockers were filled, this is false. MUST be false whenever `solvable` is true; the two are alternatives, not a scale. MUST NOT be true with an empty `blockers` array — "nearly solvable but I cannot say what is missing" is a guess, and it would put the ticket on a watch list with no condition that could ever clear it. When true, you MUST also include the label "agent:watching" in the top-level `labels` array, and when it is false that label MUST NOT appear there.',
        },
        confidence: {
          type: "string",
          enum: ["low", "med", "high"],
          description:
            "How much weight this call bears. Note that you are judging from the ticket and the knowledge vault only — you have not read the source — so `high` should be rare and means the vault names the exact file and mechanism.",
        },
        repo: {
          type: "string",
          description:
            "The single repository the fix would land in, exactly as named in the vault index (e.g. buy-insurance-advisor-web). Empty string if unknown or if more than one repo is involved — which is itself a reason for `solvable: false`.",
        },
        rationale: {
          type: "string",
          description:
            "One sentence: why an agent could, or could not, do this unattended. Name the deciding factor rather than restating the verdict.",
        },
        blockers: {
          type: "array",
          items: { type: "string" },
          description:
            'What stands in the way, one short phrase each — e.g. "needs a product decision on copy", "touches the payment schema", "no reproduction steps". MUST be empty when `solvable` is true, and should name at least one item when it is false. When `plausible` is true this list is not an explanation but a to-do list addressed to the reporter — it is the exact condition that would end the watch, so write each entry as something a person can go and do. NEVER list an unmet DoR row 8 (size) or row 9 (baseline metric / evidence) here. Those rows are advisory: they say how well the ticket is measured, not whether an agent could fix it, and an unsized or unmeasured ticket with testable acceptance criteria is still solvable. Listing one would refuse the ticket for a reason the checklist has already declined to block on.',
        },
      },
    },
  },
} as const;

export const TRIAGE_SCHEMA_JSON = JSON.stringify(TRIAGE_SCHEMA);
