/**
 * Structured-output contract for a triage run.
 *
 * Passed to Claude Code via `--json-schema`, which takes inline JSON (verified
 * by probing the arg parser: a path argument is rejected with
 * "not valid JSON: Unrecognized token '/'"). Draft-07.
 *
 * When the model's reply does not validate, Claude Code re-prompts and
 * eventually gives up with subtype `error_max_structured_output_retries`, so
 * the schema is kept deliberately small — every extra required field is
 * another way for a run to fail after paying for the work.
 */

export const TRIAGE_SCHEMA = {
  $schema: "http://json-schema.org/draft-07/schema#",
  type: "object",
  additionalProperties: false,
  required: ["verdict", "labels", "dorPlaceholders", "recommendedNextStep", "report", "mutation"],
  properties: {
    verdict: {
      type: "string",
      enum: ["duplicate", "not-our-team", "out-of-scope", "needs-info", "ready-ish"],
      // The skill's own banners are ✅ ACCEPT / ⛔ REJECT / ↪ ROUTE / ↩ SEND
      // BACK, so the mapping is spelled out here rather than left to be
      // guessed. `out-of-scope` earns its place the hard way: without it a
      // live run picked `needs-info` as "closest" and said so in its own
      // caveat, which reads as "go ask the reporter" for a ticket that wants
      // nothing of the sort.
      description:
        'The verdict, taken from the report banner. "ACCEPT" is ready-ish. "REJECT → duplicate" (or possible duplicate) is duplicate. "REJECT → out-of-scope" is out-of-scope. "ROUTE" is not-our-team. "SEND BACK" is needs-info.',
    },
    labels: {
      type: "array",
      items: { type: "string" },
      description:
        "Suggested Jira labels, e.g. dup:open, dup:solved, dor:gaps, dor:pass, route:ours, route:other-team.",
    },
    dorPlaceholders: {
      type: "array",
      items: { type: "string" },
      // Doubles as an instruction. The model reads this description, so stating
      // the rule here is the cheapest place to state it — and it is a rule the
      // skill already has: DOR_CHECKLIST.md line 28 says `dor:pass` is emitted
      // "only if 1–9 hold", and row 9 is the baseline metric. A run once
      // reported "baseline [N] left unfilled" in its own scorecard and marked
      // the row green anyway, which is what this field exists to make
      // impossible to do silently.
      description:
        'Literal unfilled fill-in placeholders still present in the ticket body, verbatim — e.g. "[N]", "[TBD]", "<beløp>". Empty array if there are none. A placeholder standing in for the DoR row 9 baseline metric means row 9 does not hold; since `dor:pass` may be emitted ONLY if rows 1–9 all hold, a non-empty array here requires `dor:gaps` rather than `dor:pass`, and rules out the "ready-ish" verdict.',
    },
    recommendedNextStep: {
      type: "string",
      description: "One sentence: what a human should do with this issue next.",
    },
    report: {
      type: "string",
      description: "The full triage report as markdown, in the language of the source ticket.",
    },
    mutation: {
      type: "object",
      additionalProperties: false,
      required: ["commentBody", "labelsAdd", "labelsRemove", "component", "links", "commentAction"],
      // This is the §11 payload preview, returned as data instead of only
      // printed. The skill already computes every field of it on a `--no-write`
      // run — "render the full payload preview below but do NOT offer to write"
      // — so nothing new is being asked of it, only that the render be
      // machine-readable. Capturing it is what lets the verdict be checked
      // BEFORE anything reaches the ticket: a separate run posts this verbatim,
      // and posts nothing if the check fails.
      description:
        "The exact §11 mutation payload — what a confirmed write WOULD send. Fill this in fully even on a --no-write run: it is the payload preview, rendered as data. It is never posted by this run.",
      properties: {
        commentBody: {
          type: "string",
          // §11 suppresses the DoR send-back reporter note "in preview / before
          // the operator confirms". That rule exists so a dry run does not show
          // an operator text addressed to someone it will not be sent to. Here
          // the field IS the confirmed payload, so the suppression would drop
          // the most useful part of a send-back comment — hence the override,
          // stated explicitly because the model is otherwise following §11
          // correctly by leaving it out.
          description:
            "The VERBATIM comment body to post, exactly as §11 would render it on a confirmed write. Must end with the footer sentinel line `_🤖 Generated by intake-triage · re-run the command to refresh._` and include the glyph + CONF legend. IMPORTANT: include the DoR send-back reporter note when the verdict warrants one — §11 suppresses that note in preview, but this field is the confirmed payload rather than a preview, and a send-back posted without its reporter note tells the reporter nothing.",
        },
        labelsAdd: {
          type: "array",
          items: { type: "string" },
          description:
            "The `+ add:` half of the §11 LABEL DELTA — only labels not already on the issue.",
        },
        labelsRemove: {
          type: "array",
          items: { type: "string" },
          description:
            "The `- remove:` half of the LABEL DELTA. ONLY the skill's own stale namespaced labels (route:*, dup:*, dor:*, tier:*, intake:*). Never a human label.",
        },
        component: {
          type: "string",
          description:
            "The single detected policy stream to apply (SSX Advisor, EDH, SSX Partner or SSX Nettsalg), or an empty string when uncertain or already correct.",
        },
        links: {
          type: "array",
          description:
            "Issue links to create. `duplicates` only for a dup:HIGH confirmed duplicate; `relates to` otherwise.",
          items: {
            type: "object",
            additionalProperties: false,
            required: ["type", "targetKey"],
            properties: {
              type: { type: "string", enum: ["duplicates", "relates to"] },
              targetKey: { type: "string", description: "e.g. SSX-1234" },
            },
          },
        },
        commentAction: {
          type: "string",
          enum: ["create", "update"],
          description:
            "Whether a comment satisfying BOTH the skill's own Jira account authorship AND the full footer sentinel already exists (update) or not (create).",
        },
      },
    },
  },
} as const;

export const TRIAGE_SCHEMA_JSON = JSON.stringify(TRIAGE_SCHEMA);
