import { describe, expect, it } from "vitest";

import type { IssueActivity } from "../jira/client.ts";
import { FOOTER_SENTINEL } from "../triage/gate.ts";
import { decideWatch, isOurComment } from "./decide.ts";
import { toWatchSignals } from "./signals.ts";

/** The footer as Jira actually stores it: text under an `em` mark, with the `_…_` markdown delimiters not in the payload. */
function footerAdf(lead: string): unknown {
  return {
    type: "doc",
    version: 1,
    content: [
      { type: "paragraph", content: [{ type: "text", text: lead }] },
      {
        type: "paragraph",
        content: [
          {
            type: "text",
            text: "🤖 Generated by intake-triage · re-run the command to refresh.",
            marks: [{ type: "em" }],
          },
        ],
      },
    ],
  };
}

function activity(overrides: Partial<IssueActivity> = {}): IssueActivity {
  return {
    key: "SSX-1234",
    statusCategoryKey: "indeterminate",
    labels: [],
    comments: [],
    changes: [],
    content: { summary: "", description: null, environment: null, attachments: [] },
    ...overrides,
  };
}

describe("toWatchSignals", () => {
  it("renders a stored footer back into something isOurComment recognises", () => {
    // A comparison against the sentinel whole would match nothing here, since
    // ADF drops the `_…_` delimiters and `renderAdf` restores them as `*…*`.
    const signals = toWatchSignals(
      activity({
        comments: [
          {
            id: "1",
            author: "someone",
            created: "2026-09-01T10:00:00.000+0200",
            updated: "2026-09-01T10:00:00.000+0200",
            body: footerAdf("Fill in the baseline."),
          },
        ],
      }),
    );

    expect(signals.comments[0]?.text).not.toContain(FOOTER_SENTINEL);
    expect(isOurComment(signals.comments[0] ?? { created: "", updated: "", text: "" })).toBe(true);
  });

  it("carries the edit timestamp, which is the one our own comment moves on", () => {
    // The poster rewrites its own comment on a re-triage, so `updated` is the
    // only field saying when this service last spoke.
    const signals = toWatchSignals(
      activity({
        comments: [
          {
            id: "1",
            author: "someone",
            created: "2026-09-01T10:00:00.000+0200",
            updated: "2026-09-05T14:00:00.000+0200",
            body: footerAdf("Fill in the baseline."),
          },
        ],
      }),
    );

    expect(signals.comments[0]?.updated).toBe("2026-09-05T14:00:00.000+0200");
  });

  it("does not claim a reporter's comment", () => {
    const signals = toWatchSignals(
      activity({
        comments: [
          {
            id: "1",
            author: "reporter",
            created: "2026-09-02T08:00:00.000+0200",
            updated: "2026-09-02T08:00:00.000+0200",
            body: {
              type: "doc",
              version: 1,
              content: [
                { type: "paragraph", content: [{ type: "text", text: "Baseline is 42%." }] },
              ],
            },
          },
        ],
      }),
    );

    expect(isOurComment(signals.comments[0] ?? { created: "", updated: "", text: "" })).toBe(false);
  });

  it("reads closed off the category key rather than the status name", () => {
    // This board's done status is not called "Done" — it's Norwegian.
    expect(toWatchSignals(activity({ statusCategoryKey: "done" })).closed).toBe(true);
    expect(toWatchSignals(activity({ statusCategoryKey: "Done" })).closed).toBe(true);
    expect(toWatchSignals(activity({ statusCategoryKey: "indeterminate" })).closed).toBe(false);
    expect(toWatchSignals(activity({ statusCategoryKey: "new" })).closed).toBe(false);
    expect(toWatchSignals(activity({ statusCategoryKey: "" })).closed).toBe(false);
  });

  it("carries the changelog through with its field names unfolded", () => {
    // The fold belongs to the decision; doing it here too would put the same
    // rule in two places.
    const signals = toWatchSignals(
      activity({
        changes: [{ created: "2026-09-02T09:00:00.000+0200", fields: ["Description", "labels"] }],
      }),
    );

    expect(signals.changes[0]?.fields).toEqual(["Description", "labels"]);
  });

  it("carries a whole ticket through to a decision", () => {
    // End to end over both modules — the seam between them is where the sentinel was lost.
    const answered = toWatchSignals(
      activity({
        comments: [
          {
            id: "1",
            author: "op",
            created: "2026-09-01T10:00:00.000+0200",
            updated: "2026-09-01T10:00:00.000+0200",
            body: footerAdf("Fill in the baseline."),
          },
        ],
        changes: [{ created: "2026-09-02T09:00:00.000+0200", fields: ["description"] }],
      }),
    );

    expect(decideWatch(answered, 3)).toMatchObject({ kind: "retriage" });
  });
});
