import { describe, expect, it } from "vitest";

import type { IssueActivity } from "../jira/client.ts";
import { FOOTER_SENTINEL } from "../triage/gate.ts";
import { decideWatch, isOurComment } from "./decide.ts";
import { toWatchSignals } from "./signals.ts";

/**
 * The footer as Jira actually stores it: a paragraph whose text sits under an
 * `em` mark, because the poster wrote it as `_…_` markdown and the API
 * converted it. The delimiters are not in the payload — that is the point.
 */
function footerAdf(lead: string): unknown {
  return {
    type: "doc",
    version: 1,
    content: [
      { type: "paragraph", content: [{ type: "text", text: lead }] },
      {
        type: "paragraph",
        content: [
          {
            type: "text",
            text: "🤖 Generated by intake-triage · re-run the command to refresh.",
            marks: [{ type: "em" }],
          },
        ],
      },
    ],
  };
}

function activity(overrides: Partial<IssueActivity> = {}): IssueActivity {
  return {
    key: "SSX-1234",
    statusCategoryKey: "indeterminate",
    labels: [],
    comments: [],
    changes: [],
    content: { summary: "", description: null, environment: null, attachments: [] },
    ...overrides,
  };
}

describe("toWatchSignals", () => {
  it("renders a stored footer back into something isOurComment recognises", () => {
    // THE test in this file, and the one that found the defect. The sentinel is
    // written `_…_`; ADF keeps the words and drops the underscores; `renderAdf`
    // puts emphasis back as `*…*`. So a check comparing the sentinel whole
    // matches nothing, every watched ticket reads as having no comment of ours,
    // and the whole population is refused as uncountable — or, with the
    // refusal removed, re-triaged forever. Reasoning about it said it was fine.
    const signals = toWatchSignals(
      activity({
        comments: [
          {
            id: "1",
            author: "someone",
            created: "2026-09-01T10:00:00.000+0200",
            updated: "2026-09-01T10:00:00.000+0200",
            body: footerAdf("Fill in the baseline."),
          },
        ],
      }),
    );

    expect(signals.comments[0]?.text).not.toContain(FOOTER_SENTINEL);
    expect(isOurComment(signals.comments[0] ?? { created: "", updated: "", text: "" })).toBe(true);
  });

  it("carries the edit timestamp, which is the one our own comment moves on", () => {
    // The poster does not add a second comment on a re-triage; it finds its own
    // by the sentinel and rewrites it. So `created` on our comment names the
    // first triage forever and `updated` is the only field that says when this
    // service last spoke. Dropping it here reads as a mark days in the past,
    // which re-triages the same activity on every sweep.
    const signals = toWatchSignals(
      activity({
        comments: [
          {
            id: "1",
            author: "someone",
            created: "2026-09-01T10:00:00.000+0200",
            updated: "2026-09-05T14:00:00.000+0200",
            body: footerAdf("Fill in the baseline."),
          },
        ],
      }),
    );

    expect(signals.comments[0]?.updated).toBe("2026-09-05T14:00:00.000+0200");
  });

  it("does not claim a reporter's comment", () => {
    const signals = toWatchSignals(
      activity({
        comments: [
          {
            id: "1",
            author: "reporter",
            created: "2026-09-02T08:00:00.000+0200",
            updated: "2026-09-02T08:00:00.000+0200",
            body: {
              type: "doc",
              version: 1,
              content: [
                { type: "paragraph", content: [{ type: "text", text: "Baseline is 42%." }] },
              ],
            },
          },
        ],
      }),
    );

    expect(isOurComment(signals.comments[0] ?? { created: "", updated: "", text: "" })).toBe(false);
  });

  it("reads closed off the category key rather than the status name", () => {
    // This board is Norwegian, so its done status is not called "Done". A
    // comparison against the name would be a watch that never ends here and
    // passes every test written in English.
    expect(toWatchSignals(activity({ statusCategoryKey: "done" })).closed).toBe(true);
    expect(toWatchSignals(activity({ statusCategoryKey: "Done" })).closed).toBe(true);
    expect(toWatchSignals(activity({ statusCategoryKey: "indeterminate" })).closed).toBe(false);
    expect(toWatchSignals(activity({ statusCategoryKey: "new" })).closed).toBe(false);
    expect(toWatchSignals(activity({ statusCategoryKey: "" })).closed).toBe(false);
  });

  it("carries the changelog through with its field names unfolded", () => {
    // The fold belongs to the decision, which is tested against it. Folding
    // here as well would put the same rule in two places, and the one without a
    // test is the one that would change.
    const signals = toWatchSignals(
      activity({
        changes: [{ created: "2026-09-02T09:00:00.000+0200", fields: ["Description", "labels"] }],
      }),
    );

    expect(signals.changes[0]?.fields).toEqual(["Description", "labels"]);
  });

  it("carries a whole ticket through to a decision", () => {
    // End to end over the two modules, because each is convincing alone and the
    // seam between them is where the sentinel was lost.
    const answered = toWatchSignals(
      activity({
        comments: [
          {
            id: "1",
            author: "op",
            created: "2026-09-01T10:00:00.000+0200",
            updated: "2026-09-01T10:00:00.000+0200",
            body: footerAdf("Fill in the baseline."),
          },
        ],
        changes: [{ created: "2026-09-02T09:00:00.000+0200", fields: ["description"] }],
      }),
    );

    expect(decideWatch(answered, 3)).toMatchObject({ kind: "retriage" });
  });
});
